# Generated by Django 5.1.15 on 2026-04-18 21:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reviews_generated', models.IntegerField(default=0)),
                ('reviews_submitted', models.IntegerField(default=0)),
                ('negative_redirects', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('language_breakdown', models.JSONField(blank=True, default=dict)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='businesses.location')),
            ],
            options={
                'verbose_name_plural': 'Daily stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location', '-date'], name='analytics_d_locatio_597557_idx')],
                'unique_together': {('location', 'date')},
            },
        ),
    ]
