# Generated by Django 5.1.15 on 2026-04-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review_count', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_snapshots', to='businesses.business')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['business', '-date'], name='analytics_g_busines_3f9684_idx')],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
