# Generated by Django 5.1.15 on 2026-04-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField()),
                ('feedback_text', models.TextField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_feedback', to='businesses.location')),
            ],
            options={
                'verbose_name_plural': 'Private feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location', 'is_read', '-created_at'], name='feedback_pr_locatio_0ebb2b_idx')],
            },
        ),
    ]
