# Generated by Django 5.1.15 on 2026-04-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_photo_url',
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
