# Generated by Django 5.1.15 on 2026-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_google_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café / Coffee shop'), ('bar_pub', 'Bar / Pub'), ('bakery', 'Bakery'), ('sweet_shop', 'Sweet shop (Mithai)'), ('ice_cream_parlour', 'Ice cream / dessert parlour'), ('fast_food', 'Fast food / QSR'), ('food_truck', 'Food truck / Street-style'), ('tiffin_service', 'Tiffin / Home food service'), ('juice_bar', 'Juice / Shake bar'), ('hotel', 'Hotel'), ('guesthouse_lodge', 'Guesthouse / Lodge'), ('resort', 'Resort'), ('homestay', 'Homestay / Bed & Breakfast'), ('clinic', 'Clinic / Doctor'), ('dental_clinic', 'Dental clinic'), ('hospital', 'Hospital / Multi-specialty'), ('diagnostics_lab', 'Diagnostics / Pathology lab'), ('pharmacy', 'Pharmacy / Medical store'), ('veterinary', 'Veterinary clinic / Pet'), ('optical_store', 'Optical store'), ('salon', 'Salon / Beauty parlour'), ('spa', 'Spa / Massage'), ('barber_shop', 'Barber shop'), ('nail_studio', 'Nail studio'), ('mehendi_artist', 'Mehendi / Henna artist'), ('gym', 'Gym / Fitness centre'), ('yoga_studio', 'Yoga studio'), ('fitness_trainer', 'Personal trainer / Coach'), ('dance_studio', 'Dance / Music studio'), ('retail', 'Retail store (general)'), ('kirana_store', 'Kirana / Grocery store'), ('supermarket', 'Supermarket'), ('clothing_store', 'Clothing / Apparel store'), ('jewelry_store', 'Jewellery store'), ('electronics_store', 'Electronics store'), ('mobile_shop', 'Mobile / Phone store'), ('footwear_store', 'Footwear / Shoe store'), ('cosmetics_shop', 'Cosmetics / Beauty shop'), ('hardware_store', 'Hardware store'), ('book_stationery', 'Book / Stationery store'), ('furniture_store', 'Furniture / Home decor'), ('agri_seed_store', 'Agri / Seed / Fertiliser'), ('car_service', 'Car service / Garage'), ('bike_service', 'Bike / Two-wheeler service'), ('car_wash', 'Car / Bike wash'), ('petrol_pump', 'Petrol pump / Fuel station'), ('car_dealer', 'Car / Vehicle dealership'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('painter_contractor', 'Painter / Contractor'), ('cleaning_service', 'Home cleaning / Pest control'), ('school', 'School'), ('coaching_institute', 'Coaching institute'), ('tuition_classes', 'Tuition classes'), ('preschool_daycare', 'Preschool / Daycare'), ('photography_studio', 'Photography studio'), ('event_wedding_planner', 'Event / Wedding planner'), ('travel_agency', 'Travel agency / Tour'), ('real_estate_agent', 'Real estate / Property'), ('tailor', 'Tailor / Boutique'), ('laundry_drycleaner', 'Laundry / Dry cleaner'), ('mobile_repair', 'Mobile repair'), ('computer_repair', 'Computer / Laptop repair'), ('appliance_repair', 'Appliance / AC repair'), ('watch_repair', 'Watch / Jewellery repair'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
