# Generated by Django 5.1.15 on 2026-04-18 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('star_rating', models.IntegerField()),
                ('selected_categories', models.JSONField(blank=True, default=list)),
                ('selected_items', models.JSONField(blank=True, default=list)),
                ('language_mode_used', models.CharField(blank=True, max_length=20)),
                ('tone_mode_used', models.CharField(blank=True, max_length=20)),
                ('is_negative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='businesses.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_number', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('tone', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('was_selected', models.BooleanField(default=False)),
                ('was_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='reviews.reviewrequest')),
            ],
            options={
                'ordering': ['variant_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='reviews.reviewvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['location', '-created_at'], name='reviews_rev_locatio_36e4bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvariant',
            unique_together={('request', 'variant_number')},
        ),
    ]
