# Generated by Django 5.1.15 on 2026-04-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_mode', models.CharField(choices=[('hinglish', 'Hinglish'), ('minglish', 'Minglish (Marathi + English)'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('english', 'English'), ('random', 'Random mix')], default='random', max_length=20)),
                ('tone_mode', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('enthusiastic', 'Enthusiastic'), ('random', 'Random mix')], default='random', max_length=20)),
                ('allow_customer_language_change', models.BooleanField(default=True)),
                ('review_length', models.CharField(choices=[('short', 'Short (1-2 sentences)'), ('medium', 'Medium (3-4 sentences)'), ('detailed', 'Detailed (5-7 sentences)')], default='medium', max_length=20)),
                ('mention_business_name', models.BooleanField(default=True)),
                ('negative_filter_threshold', models.IntegerField(default=2)),
                ('custom_keywords', models.JSONField(blank=True, default=list)),
                ('blocked_phrases', models.JSONField(blank=True, default=list)),
                ('categories_enabled', models.JSONField(blank=True, default=dict)),
                ('menu_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'Business settings',
            },
        ),
        migrations.CreateModel(
            name='LocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_override', to='businesses.location')),
            ],
            options={
                'verbose_name_plural': 'Location settings',
            },
        ),
    ]
