# Generated by Django 5.1.15 on 2026-04-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_business_type'),
        ('settings_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='language_mode',
            field=models.CharField(choices=[('english', 'English'), ('hinglish', 'Hinglish (Roman script)'), ('hinglish_devanagari', 'Hinglish (देवनागरी script)'), ('hindi', 'Hindi (हिंदी)'), ('marathi', 'Marathi (मराठी)'), ('minglish', 'Minglish (Marathi + English)'), ('random', 'Random mix')], default='random', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='businesses.business')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='settings_mgr.businesscategory')),
            ],
            options={
                'verbose_name': 'Business category',
                'verbose_name_plural': 'Business categories',
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('business', 'parent', 'key'), name='uniq_category_per_business')],
            },
        ),
    ]
