# Generated by Django 5.1.15 on 2026-04-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_mgr', '0003_backfill_business_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssettings',
            name='categories_enabled',
        ),
    ]
